apiVersion: v1
kind: Secret
metadata:
  name: rke2-etcd-details
  namespace: etcd-backup-rke2
  annotations:
    kanister.kasten.io/blueprint: rke2-etcd-snapshot-only
type: Opaque
stringData:
  snapshotDir: "/var/lib/rancher/rke2/server/db/snapshots"
